### ISSUE TITLE
Crashed while writing out image

### ISSUE THREAD

**Issue by charleswg** [jonclayden/RNiftyReg#10]
I tried reading two sets of images (512,512,67) and did an affine registration.

It finished fine but when I tried to write the result out, it crashed. Any idea how to avoid it?

When I tried nonlinear registration using the affine results as init, it reached the iteration limit. Again, writing it out would crash.

As a comparison, I read the image in and write it out, it will not crash. I was not out of memory (128GB) with just a few image volumes. 

I also install from source on RNifti and still have crashing issue.

Update:
Resolved by writeNifti(result$image,'filename.nii.gz')

**Comment by jonclayden** [comment]
Hi. Thanks for updating the issue with your resolution, but could you let me know what your code was before, that led to the crash? Any crashing bug is worth knowing about.

**Comment by charleswg** [comment]
Thanks for the quick response. I think it's more to do with early stumbles modeling after the instructions. Maybe it's windows related? Also, how can I turn on the GPU mode for NVIDIA card as I saw it's already there? Thanks.

----
library(RNiftyReg)

setwd("c:/Casedirectory/")

% The following codes failed to work as the system.file part returns ""
source <- readNifti(system.file("extdata", "file1.gz", package="RNiftyReg"))
target <- readNifti(system.file("extdata", "file2.nii.gz", package="RNiftyReg"))

result <- niftyreg(source, target)

----
library(RNiftyReg)

setwd("c:/Casedirectory/")

% The following codes now works
source <- readNifti("file1.gz")
target <- readNifti("file2.nii.gz")

result <- niftyreg(source, target)

% This usage crashed without warnings. It'd be nice for it to just work this way as intended
writeNifti(result,'filename.nii.gz')

**Comment by jonclayden** [comment]
OK, I see – so the issue is when you try and pass the whole registration result object to `writeNifti` instead of just the image. I'll look into that – thanks.

As for CUDA support, I'm afraid it isn't available through this interface, not least because I don't have suitable hardware to test it on. You'll need to use the NiftyReg command-line interface to get GPU acceleration to work.

**Comment by jonclayden** [comment]
Thanks again for raising this. With `RNifti` 1.2.0 or later, and the development version of `RNiftyReg`, it should now be possible to run `writeNifti(result,'filename.nii.gz')`.
