### ISSUE TITLE
Formats that can be used.

### ISSUE THREAD

**Issue by ms-program** [jonclayden/RNiftyReg#12]
I want to use niftyreg with DICOM images.
Can I use dcm format files in niftyreg?

**Comment by jonclayden** [comment]
Hi. `RNiftyReg` doesn't read DICOM directly, but if you install the [`divest` package](https://github.com/jonclayden/divest), you can use its `readDicom()` function and pass the resulting images straight to `niftyreg()`.

**Comment by jonclayden** [comment]
I assume I've answered the question, so I'll close the issue.

**Comment by ms-program** [comment]
Thank you for your answer. I was able to convert from DICOM.
I did registration in Reg f3d and specified the resulting file as a trans file in Reg Jacobian, but I couldn't get the jacobian.
What kind of files should I use for the trans files in Reg transform and RegJacobian?

**Comment by jonclayden** [comment]
Are you able to post the code you're using? You should be able to obtain the Jacobian of a transformation without writing any files if you're using `RNiftyReg`. If you're using the NiftyReg command-line then you'd be better raising the issue against the [NiftyReg repository](https://github.com/KCL-BMEIS/niftyreg), because I don't maintain that interface.

**Comment by ms-program** [comment]
Thanks for the answer.
I used to use NiftyReg on linux but it didn't work so I'll use RNiftyReg to calculate jacobian.
I used Git's "README.md" and "Package 'RNiftyReg" as a reference.
The "README.md" command
library(RNiftyReg)
image <- readNifti(system.file("extdata", "epi_t2.nii.gz", package="RNiftyReg")), where "extdata" is the DICOM image folder to be used, then "nifti_image_ A "read: failed to find header file for" error occurred.

↓ The code used
(RNiftyReg)
> image <- readNifti(system.file("C:/Users/Desktop/DIR-DB/2_PLAN1", "epi_t2.nii.gz", package="RNiftyReg"))

**Comment by jonclayden** [comment]
Hi. In this case you're taking the example code slightly too literally – the `system.file()` function is only for accessing files provided with packages, and since you're reading from DICOM, not NIfTI, you need to use `readDicom()` as I mentioned above, viz.

```r
# Install divest first, if necessary (remove the comment character)
# install.packages("divest")
images <- divest::readDicom("C:/Users/Desktop/DIR-DB/2_PLAN1")
```

That will give you a list of images, which you can pass to the `source` and/or `target` arguments of `niftyreg()`, as needed. Then, to get the Jacobian of resulting transformation, you can use

```r
library(RNiftyReg)

# Perform the registration first, and store the result
# result <- niftyreg(...)
jac <- jacobian(deformationField(forward(result)))
```

**Comment by ms-program** [comment]
Thanks for the answer.
"images <- divest::readDicom" with the DICOM folder, so I was able to load it.
[dcm2niix info] Found 168 DICOM file(s)
[dcm2niix WARNING] Empty protocol name(s) (0018,1030)
[dcm2niix WARNING] Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor.
[dcm2niix WARNING] Interslice distance varies in this volume (incompatible with NIfTI format).
[dcm2niix WARNING] Order specified by DICOM instance number is not spatial (reordering).
[dcm2niix info] Slice re-ordering resolved inter-slice distance variability.
Missing images? Expected 168 images, but instance number (0020,0013) ranges from 41 to 26.
[dcm2niix info] Convert 168 DICOM as T20170601133657_N2_S1 (512x512x168x1)

However, if I use this function to specify a folder with "RTstructure" or a registration image that has a DVF, I get an error like the following.
[dcm2niix info] Found 1 DICOM file(s)
[dcm2niix info] No valid DICOM images were found
No valid DICOM files found
Can't use such images?

Also, in source and target, I specified the read DICOM folder in "source <- readNifti", but an error occurred.
source <- readNifti("C:/Users/Desktop/DIR-DB/2_PLAN1/2_PLAN1_CT")
nifti_image_read: failed to find header file for 'C:/Users/Desktop/DIRDB/2_PLAN1/2_PLAN1_CT'

**Comment by jonclayden** [comment]
I'm afraid I don't know what "RTstructure" is, and I don't know why you're reverting to `readNifti()` at the end here. **You cannot pass a DICOM directory to `readNifti()`**, and there is no need to because `readDicom()` will return appropriate images. I'll try and run through the full pipeline in example code.

```r
library(divest)
library(RNiftyReg)

source <- readDicom("source_path")  #< Substitute the DICOM directory path
                                    #< containing the source image here, and
                                    #< select it (only) during the interactive
                                    #< step

target <- readDicom("target_path")  #< Likewise for the path containing the
                                    #< target image (which may be the same)

result <- niftyreg(source[[1]], target[[1]])    #< Perform the registration.
                                                #< readDicom() returns a list
                                                #< of images, which is why the
                                                #< [[1]] syntax is needed

jac <- jacobian(deformationField(forward(result)))  #< Extract the Jacobian
```

**Comment by ms-program** [comment]
Thanks for the answer.
RTstrcture is an image file containing the contour information created by the treatment plan.
I was asking if it can be used with image files that have contour and dose information.
I'm sorry I didn't explain it enough.

I tried the method you gave me, but when I enter "> result <- niftyreg(source[[1]], target[[1]])",
" niftyreg.linear(source, target, scope, scope, init, sourceMask, targetMask, " generated an error and displayed "Source image should have 2, 3 or 4 dimensions".
To find the cause of this error, I would like to see the images used and the results of the registration as images.
> library(divest)
> library(RNiftyReg)
> image <- readDicom("C:/Users/Desktop/DIRDB/2_PLAN1/2_PLAN1_CT")
However, this input did not show up as an image.
How can I improve the input and results to be viewed as an image?

**Comment by ms-program** [comment]
Thanks for the answer.
RTstrcture is an image file containing the contour information created by the treatment plan.
I was asking if it can be used with image files that have contour and dose information.
I'm sorry I didn't explain it enough.

I tried the method you gave me, but when I enter "> result <- niftyreg(source[[1]], target[[1]])",
" niftyreg.linear(source, target, scope, scope, init, sourceMask, targetMask, " generated an error and displayed "Source image should have 2, 3 or 4 dimensions".
To find the cause of this error, I would like to see the images used and the results of the registration as images.

library(divest)
library(RNiftyReg)
image <- readDicom("C:/Users/Desktop/DIRDB/2_PLAN1/2_PLAN1_CT")

However, this input did not show up as an image.
How can I improve the input and results to be viewed as an image?

**Comment by jonclayden** [comment]
> RTstrcture is an image file containing the contour information created by the treatment plan.
> I was asking if it can be used with image files that have contour and dose information.
> I'm sorry I didn't explain it enough.

It depends on the basic format. If it's DICOM or NIfTI or a standard image type (JPEG, PNG, etc.), or any other file type for which a reader exists in some R package that will convert it to an array, then yes, you can probably use it. If it's a custom/proprietary format for which there's no reader, then probably not. But I can't be more specific without knowing the details. If there's a specification of the format online somewhere, perhaps you could point to that?

> I tried the method you gave me, but when I enter "> result <- niftyreg(source[[1]], target[[1]])",
> " niftyreg.linear(source, target, scope, scope, init, sourceMask, targetMask, " generated an error and displayed "Source image should have 2, 3 or 4 dimensions".

You may be bumping into issue #11. It's worth updating `RNifti` to v1.2.2 and `RNiftyReg` to v2.7.0, if you haven't already.

> To find the cause of this error, I would like to see the images used and the results of the registration as images.

Sure – you can use `RNifti`'s image viewer to see the images, viz. `RNifti::view(source[[1]])` etc.

**Comment by ms-program** [comment]
I updated the "RNiftyReg" and got the "result" successfully. Thank you very much.
I typed "jac <- jacobian(informationField(forward(result))))" after "result" and it didn't give me any output, although I didn't get an error.
If successful, what format does "jacobian" take?

**Comment by jonclayden** [comment]
Great! The command should have created an image called `jac` containing the value of the Jacobean determinant at each pixel/voxel. You should be able to view it with `RNifti::view(jac)`.

**Comment by ms-program** [comment]
I was able to get a " jacobian". Thank you very much.

I have an additional question.
1. What is the registration algorithm  used in this process?
　Is the number listed in "applyTransform" in "Package 'RNiftyReg'" an algorithm?(0 (nearest neighbour), 1 (trilinear) or 3 (cubic 　spline))
　In that case, if I change the number entered in [[ ]] of "result <- niftyreg(source[[1]], target[[1]])", will the algorithm also 
　change?
　"result <- niftyreg(source[[3]], target[[3]])", an error occurred with "source".
2. I want to save a converted NIfTI image file from DICOM in NIfTI format and not as a metafile. How do I save them?

**Comment by jonclayden** [comment]
> I was able to get a " jacobian". Thank you very much.

No problem.

> 1. What is the registration algorithm  used in this process?

There's a brief description in the documentation (see `?niftyreg.linear`), but for full details you'll need to consult [the paper](https://doi.org/10.1117/1.JMI.1.2.024003).

>    　Is the number listed in "applyTransform" in "Package 'RNiftyReg'" an algorithm?(0 (nearest neighbour), 1 (trilinear) or 3 (cubic 　spline))

No, this is the order of the interpolation used. If you're not familiar with interpolation, you can read about it [on Wikipedia](https://en.wikipedia.org/wiki/Interpolation) or elsewhere.

>    　In that case, if I change the number entered in [[ ]] of "result <- niftyreg(source[[1]], target[[1]])", will the algorithm also
>    　change?
>    　"result <- niftyreg(source[[3]], target[[3]])", an error occurred with "source".

No. You're changing the index value into the list, attempting to read the third image rather than the first (which probably doesn't exist, hence the error). If you want to change the interpolation order, you need to set the `interpolation` argument to the appropriate value, viz.

```r
result <- niftyreg(source[[1]], target[[1]], interpolation=3)
```

(although 3 is the default). If the logic of this doesn't make sense to you then it might be helpful to look up a guide to the fundamentals of R's syntax – there are plenty online, and they're not hard to find.

> 2. I want to save a converted NIfTI image file from DICOM in NIfTI format and not as a metafile. How do I save them?

You can save images to NIfTI files with `RNifti::writeNifti(image, filename)`, substituting the appropriate image object and file name string.

**Comment by ms-program** [comment]
Thanks for the answer.

If I want to save the source, should I just type  "source" for "filename" in "RNifti::writeNifti(image, filename)"?
RNifti::writeNifti(image, source)
Is it correct to create your own files, like "source.nii"?

Is it possible to get jacobian from a DVF (DCM file) created by another software directly?
If this is possible, where do I put the file in "jacobian(x)" as listed in "Package 'RNiftyReg'"?

**Comment by jonclayden** [comment]
`source` is presumably the image here, so it should go as the first argument. The second can be anything you like, as you say.

Other software may use a different format for the Jacobian, so I would not assume compatibility, no.
