### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/RNiftyReg#14]
Using with CRAN version.  Trying to register 2 images and then apply the transformation.  I figure if there is only 1 affine, then it should still be a list, but it seems as though when you look in `applyTransform` you look in attributes that don't exist:

    library(MNITemplate)
    library(EveTemplate)
    #> Loading required package: oro.nifti
    #> oro.nifti 0.11.0
    library(RNiftyReg)
    #> 
    #> Attaching package: 'RNiftyReg'
    #> The following objects are masked from 'package:oro.nifti':
    #> 
    #>     pixdim, pixdim<-
    mni = readNifti(getMNIPath())
    eve = readNifti(getEvePath())
    reg = niftyreg(source = mni, target = eve, scope = "rigid", verbose = TRUE)
    #> [reg_aladin_sym] Parameters
    #> [reg_aladin_sym] Platform: cpu_platform
    #> [reg_aladin_sym] Reference image name: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/EveTemplate/extdata/JHU_MNI_SS_T1.nii.gz
    #> [reg_aladin_sym]     181x217x181 voxels
    #> [reg_aladin_sym]     1x1x1 mm
    #> [reg_aladin_sym] Floating image name: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/MNITemplate/extdata/MNI152_T1_1mm.nii.gz
    #> [reg_aladin_sym]     182x218x182 voxels
    #> [reg_aladin_sym]     1x1x1 mm
    #> [reg_aladin_sym] Maximum iteration number: 5
    #> [reg_aladin_sym]     (10 during the first level)
    #> [reg_aladin_sym] Percentage of blocks: 50 %
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Current level 1 / 3
    #> [reg_aladin_sym] reference image size:   46x55x46 voxels 4x4x4 mm
    #> [reg_aladin_sym] floating image size:    46x55x46 voxels 4x4x4 mm
    #> [reg_aladin_sym] Block size = [4 4 4]
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Forward Block number = [12 14 12]
    #> [reg_aladin_sym] Backward Block number = [12 14 12]
    #> [reg_aladin_sym] Initial forward transformation matrix::
    #> 1    0   0   89.5
    #> 0    1   0   -125.5
    #> 0    0   1   -71.5
    #> 0    0   0   1
    #> [reg_aladin_sym] Initial backward transformation matrix::
    #> 1    0   0   -89.5
    #> 0    1   0   125.5
    #> 0    0   1   71.5
    #> 0    0   0   1
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Final forward transformation matrix::
    #> 0.9999968    0.002416389 -0.0006827222   90.02625
    #> -0.002410317 0.9999588   0.008756792 -125.5994
    #> 0.0007038604 -0.008755095    0.9999615   -71.12029
    #> 0    0   0   1
    #> [reg_aladin_sym] Final backward transformation matrix::
    #> 0.9999968    -0.002410319    0.0007038538    -90.27863
    #> 0.002416387  0.9999588   -0.00875512 124.754
    #> -0.0006827287    0.008756768 0.9999614   72.27885
    #> 0    0   0   1
    #> [reg_aladin_sym] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #> [reg_aladin_sym] Current level 2 / 3
    #> [reg_aladin_sym] reference image size:   91x109x91 voxels    2x2x2 mm
    #> [reg_aladin_sym] floating image size:    91x109x91 voxels    2x2x2 mm
    #> [reg_aladin_sym] Block size = [4 4 4]
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Forward Block number = [23 28 23]
    #> [reg_aladin_sym] Backward Block number = [23 28 23]
    #> [reg_aladin_sym] Initial forward transformation matrix::
    #> 0.9999968    0.002416389 -0.0006827222   90.02625
    #> -0.002410317 0.9999588   0.008756792 -125.5994
    #> 0.0007038604 -0.008755095    0.9999615   -71.12029
    #> 0    0   0   1
    #> [reg_aladin_sym] Initial backward transformation matrix::
    #> 0.9999968    -0.002410319    0.0007038538    -90.27863
    #> 0.002416387  0.9999588   -0.00875512 124.754
    #> -0.0006827287    0.008756768 0.9999614   72.27885
    #> 0    0   0   1
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Final forward transformation matrix::
    #> 0.9999942    0.0008204075    -0.003344682    90.10604
    #> -0.0008060082    0.9999904   0.004304657 -125.3186
    #> 0.00334818   -0.004301929    0.9999852   -71.21294
    #> 0    0   0   1
    #> [reg_aladin_sym] Final backward transformation matrix::
    #> 0.999994 -0.0008060067   0.003348181 -89.96807
    #> 0.0008204091 0.9999904   -0.004301935    124.9372
    #> -0.00334468  0.00430465  0.9999851   72.05271
    #> 0    0   0   1
    #> [reg_aladin_sym] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #> [reg_aladin_sym] Current level 3 / 3
    #> [reg_aladin_sym] reference image size:   181x217x181 voxels  1x1x1 mm
    #> [reg_aladin_sym] floating image size:    182x218x182 voxels  1x1x1 mm
    #> [reg_aladin_sym] Block size = [4 4 4]
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Forward Block number = [46 55 46]
    #> [reg_aladin_sym] Backward Block number = [46 55 46]
    #> [reg_aladin_sym] Initial forward transformation matrix::
    #> 0.9999942    0.0008204075    -0.003344682    90.10604
    #> -0.0008060082    0.9999904   0.004304657 -125.3186
    #> 0.00334818   -0.004301929    0.9999852   -71.21294
    #> 0    0   0   1
    #> [reg_aladin_sym] Initial backward transformation matrix::
    #> 0.999994 -0.0008060067   0.003348181 -89.96807
    #> 0.0008204091 0.9999904   -0.004301935    124.9372
    #> -0.00334468  0.00430465  0.9999851   72.05271
    #> 0    0   0   1
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Final forward transformation matrix::
    #> 0.9999995    -0.0009092297   0.0004943098    89.65136
    #> 0.0009063974 0.9999834   0.005699717 -124.6325
    #> -0.0004994795    -0.005699267    0.9999837   -71.99718
    #> 0    0   0   1
    #> [reg_aladin_sym] Final backward transformation matrix::
    #> 0.9999995    0.0009063976    -0.000499484    -89.5743
    #> -0.0009092294    0.9999833   -0.005699266    124.3016
    #> 0.0004943054 0.005699718 0.9999836   72.66205
    #> 0    0   0   1
    #> [reg_aladin_sym] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    applyTransform(transform = reg$forwardTransforms, x = mni)
    #> Error in applyTransform(transform = reg$forwardTransforms, x = mni): Specified transform is not valid

    applyTransform(transform = reg$forwardTransforms[[1]], x = mni)
    #> Error in applyTransform(transform = reg$forwardTransforms[[1]], x = mni): Object to transform should be a suitable image or matrix of points

<sup>Created on 2020-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-10-08                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib
    #>  abind         1.4-5      2016-07-21 [2]
    #>  assertthat    0.2.1      2019-03-21 [2]
    #>  backports     1.1.10     2020-09-15 [1]
    #>  bitops        1.0-6      2013-08-17 [2]
    #>  cli           2.0.2      2020-02-28 [2]
    #>  crayon        1.3.4      2017-09-16 [2]
    #>  digest        0.6.25     2020-02-23 [2]
    #>  ellipsis      0.3.1      2020-05-15 [2]
    #>  evaluate      0.14       2019-05-28 [2]
    #>  EveTemplate * 1.0.0      2020-06-01 [2]
    #>  fansi         0.4.1      2020-01-08 [2]
    #>  fs            1.5.0      2020-07-31 [2]
    #>  glue          1.4.2      2020-08-27 [1]
    #>  highr         0.8        2019-03-20 [2]
    #>  htmltools     0.5.0      2020-06-16 [2]
    #>  knitr         1.30       2020-09-22 [1]
    #>  lifecycle     0.2.0      2020-03-06 [2]
    #>  magrittr      1.5        2014-11-22 [2]
    #>  MNITemplate * 1.0.0      2020-06-01 [2]
    #>  ore           1.6.3      2019-11-02 [2]
    #>  oro.nifti   * 0.11.0     2020-09-04 [2]
    #>  pillar        1.4.6      2020-07-10 [2]
    #>  pkgconfig     2.0.3      2019-09-22 [2]
    #>  purrr         0.3.4      2020-04-17 [2]
    #>  Rcpp          1.0.5      2020-07-06 [2]
    #>  reprex        0.3.0.9001 2020-09-30 [1]
    #>  rlang         0.4.7.9000 2020-10-05 [1]
    #>  rmarkdown     2.4        2020-09-30 [1]
    #>  RNifti        1.2.2      2020-09-07 [1]
    #>  RNiftyReg   * 2.7.0      2020-09-12 [1]
    #>  rstudioapi    0.11       2020-02-07 [2]
    #>  sessioninfo   1.1.1      2018-11-05 [2]
    #>  stringi       1.5.3      2020-09-09 [1]
    #>  stringr       1.4.0      2019-02-10 [2]
    #>  styler        1.3.2      2020-02-23 [2]
    #>  tibble        3.0.3      2020-07-10 [2]
    #>  vctrs         0.3.4      2020-08-29 [1]
    #>  withr         2.3.0      2020-09-22 [1]
    #>  xfun          0.18       2020-09-29 [1]
    #>  yaml          2.2.1      2020-02-01 [2]
    #>  source                                  
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (muschellij2/EveTemplate@ed54115)
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (muschellij2/MNITemplate@46e8f81)
    #>  CRAN (R 4.0.0)                          
    #>  local                                   
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (tidyverse/reprex@d3fc4b8)       
    #>  Github (r-lib/rlang@0bce15a)            
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

# Using GitHub version

    library(MNITemplate)
    library(EveTemplate)
    #> Loading required package: oro.nifti
    #> oro.nifti 0.11.0
    library(RNiftyReg)
    #> 
    #> Attaching package: 'RNiftyReg'
    #> The following objects are masked from 'package:oro.nifti':
    #> 
    #>     pixdim, pixdim<-
    mni = readNifti(getMNIPath())
    eve = readNifti(getEvePath())
    reg = niftyreg(source = mni, target = eve, scope = "rigid", verbose = TRUE)
    #> [reg_aladin_sym] Parameters
    #> [reg_aladin_sym] Platform: cpu_platform
    #> [reg_aladin_sym] Reference image name: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/EveTemplate/extdata/JHU_MNI_SS_T1.nii.gz
    #> [reg_aladin_sym]     181x217x181 voxels
    #> [reg_aladin_sym]     1x1x1 mm
    #> [reg_aladin_sym] Floating image name: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/MNITemplate/extdata/MNI152_T1_1mm.nii.gz
    #> [reg_aladin_sym]     182x218x182 voxels
    #> [reg_aladin_sym]     1x1x1 mm
    #> [reg_aladin_sym] Maximum iteration number: 5
    #> [reg_aladin_sym]     (10 during the first level)
    #> [reg_aladin_sym] Percentage of blocks: 50 %
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Current level 1 / 3
    #> [reg_aladin_sym] reference image size:   46x55x46 voxels 4x4x4 mm
    #> [reg_aladin_sym] floating image size:    46x55x46 voxels 4x4x4 mm
    #> [reg_aladin_sym] Block size = [4 4 4]
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Forward Block number = [12 14 12]
    #> [reg_aladin_sym] Backward Block number = [12 14 12]
    #> [reg_aladin_sym] Initial forward transformation matrix::
    #> 1    0   0   89.5
    #> 0    1   0   -125.5
    #> 0    0   1   -71.5
    #> 0    0   0   1
    #> [reg_aladin_sym] Initial backward transformation matrix::
    #> 1    0   0   -89.5
    #> 0    1   0   125.5
    #> 0    0   1   71.5
    #> 0    0   0   1
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Final forward transformation matrix::
    #> 0.9999968    0.002416389 -0.0006827222   90.02625
    #> -0.002410317 0.9999588   0.008756792 -125.5994
    #> 0.0007038604 -0.008755095    0.9999615   -71.12029
    #> 0    0   0   1
    #> [reg_aladin_sym] Final backward transformation matrix::
    #> 0.9999968    -0.002410319    0.0007038538    -90.27863
    #> 0.002416387  0.9999588   -0.00875512 124.754
    #> -0.0006827287    0.008756768 0.9999614   72.27885
    #> 0    0   0   1
    #> [reg_aladin_sym] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #> [reg_aladin_sym] Current level 2 / 3
    #> [reg_aladin_sym] reference image size:   91x109x91 voxels    2x2x2 mm
    #> [reg_aladin_sym] floating image size:    91x109x91 voxels    2x2x2 mm
    #> [reg_aladin_sym] Block size = [4 4 4]
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Forward Block number = [23 28 23]
    #> [reg_aladin_sym] Backward Block number = [23 28 23]
    #> [reg_aladin_sym] Initial forward transformation matrix::
    #> 0.9999968    0.002416389 -0.0006827222   90.02625
    #> -0.002410317 0.9999588   0.008756792 -125.5994
    #> 0.0007038604 -0.008755095    0.9999615   -71.12029
    #> 0    0   0   1
    #> [reg_aladin_sym] Initial backward transformation matrix::
    #> 0.9999968    -0.002410319    0.0007038538    -90.27863
    #> 0.002416387  0.9999588   -0.00875512 124.754
    #> -0.0006827287    0.008756768 0.9999614   72.27885
    #> 0    0   0   1
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Final forward transformation matrix::
    #> 0.9999942    0.0008204075    -0.003344682    90.10604
    #> -0.0008060082    0.9999904   0.004304657 -125.3186
    #> 0.00334818   -0.004301929    0.9999852   -71.21294
    #> 0    0   0   1
    #> [reg_aladin_sym] Final backward transformation matrix::
    #> 0.999994 -0.0008060067   0.003348181 -89.96807
    #> 0.0008204091 0.9999904   -0.004301935    124.9372
    #> -0.00334468  0.00430465  0.9999851   72.05271
    #> 0    0   0   1
    #> [reg_aladin_sym] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #> [reg_aladin_sym] Current level 3 / 3
    #> [reg_aladin_sym] reference image size:   181x217x181 voxels  1x1x1 mm
    #> [reg_aladin_sym] floating image size:    182x218x182 voxels  1x1x1 mm
    #> [reg_aladin_sym] Block size = [4 4 4]
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Forward Block number = [46 55 46]
    #> [reg_aladin_sym] Backward Block number = [46 55 46]
    #> [reg_aladin_sym] Initial forward transformation matrix::
    #> 0.9999942    0.0008204075    -0.003344682    90.10604
    #> -0.0008060082    0.9999904   0.004304657 -125.3186
    #> 0.00334818   -0.004301929    0.9999852   -71.21294
    #> 0    0   0   1
    #> [reg_aladin_sym] Initial backward transformation matrix::
    #> 0.999994 -0.0008060067   0.003348181 -89.96807
    #> 0.0008204091 0.9999904   -0.004301935    124.9372
    #> -0.00334468  0.00430465  0.9999851   72.05271
    #> 0    0   0   1
    #> [reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    #> [reg_aladin_sym] Final forward transformation matrix::
    #> 0.9999995    -0.0009092297   0.0004943098    89.65136
    #> 0.0009063974 0.9999834   0.005699717 -124.6325
    #> -0.0004994795    -0.005699267    0.9999837   -71.99718
    #> 0    0   0   1
    #> [reg_aladin_sym] Final backward transformation matrix::
    #> 0.9999995    0.0009063976    -0.000499484    -89.5743
    #> -0.0009092294    0.9999833   -0.005699266    124.3016
    #> 0.0004943054 0.005699718 0.9999836   72.66205
    #> 0    0   0   1
    #> [reg_aladin_sym] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    applyTransform(transform = reg$forwardTransforms, x = mni)
    #> Error in applyTransform(transform = reg$forwardTransforms, x = mni): Specified transform is not valid

    applyTransform(transform = reg$forwardTransforms[[1]], x = mni)
    #> Error in applyTransform(transform = reg$forwardTransforms[[1]], x = mni): Object to transform should be a suitable image or matrix of points

<sup>Created on 2020-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-10-08                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib
    #>  abind         1.4-5      2016-07-21 [2]
    #>  assertthat    0.2.1      2019-03-21 [2]
    #>  backports     1.1.10     2020-09-15 [1]
    #>  bitops        1.0-6      2013-08-17 [2]
    #>  cli           2.0.2      2020-02-28 [2]
    #>  crayon        1.3.4      2017-09-16 [2]
    #>  digest        0.6.25     2020-02-23 [2]
    #>  ellipsis      0.3.1      2020-05-15 [2]
    #>  evaluate      0.14       2019-05-28 [2]
    #>  EveTemplate * 1.0.0      2020-06-01 [2]
    #>  fansi         0.4.1      2020-01-08 [2]
    #>  fs            1.5.0      2020-07-31 [2]
    #>  glue          1.4.2      2020-08-27 [1]
    #>  highr         0.8        2019-03-20 [2]
    #>  htmltools     0.5.0      2020-06-16 [2]
    #>  knitr         1.30       2020-09-22 [1]
    #>  lifecycle     0.2.0      2020-03-06 [2]
    #>  magrittr      1.5        2014-11-22 [2]
    #>  MNITemplate * 1.0.0      2020-06-01 [2]
    #>  ore           1.6.3      2019-11-02 [2]
    #>  oro.nifti   * 0.11.0     2020-09-04 [2]
    #>  pillar        1.4.6      2020-07-10 [2]
    #>  pkgconfig     2.0.3      2019-09-22 [2]
    #>  purrr         0.3.4      2020-04-17 [2]
    #>  Rcpp          1.0.5      2020-07-06 [2]
    #>  reprex        0.3.0.9001 2020-09-30 [1]
    #>  rlang         0.4.7.9000 2020-10-05 [1]
    #>  rmarkdown     2.4        2020-09-30 [1]
    #>  RNifti        1.2.2      2020-09-07 [1]
    #>  RNiftyReg   * 2.7.0      2020-10-08 [1]
    #>  rstudioapi    0.11       2020-02-07 [2]
    #>  sessioninfo   1.1.1      2018-11-05 [2]
    #>  stringi       1.5.3      2020-09-09 [1]
    #>  stringr       1.4.0      2019-02-10 [2]
    #>  styler        1.3.2      2020-02-23 [2]
    #>  tibble        3.0.3      2020-07-10 [2]
    #>  vctrs         0.3.4      2020-08-29 [1]
    #>  withr         2.3.0      2020-09-22 [1]
    #>  xfun          0.18       2020-09-29 [1]
    #>  yaml          2.2.1      2020-02-01 [2]
    #>  source                                  
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (muschellij2/EveTemplate@ed54115)
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (muschellij2/MNITemplate@46e8f81)
    #>  CRAN (R 4.0.0)                          
    #>  local                                   
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  Github (tidyverse/reprex@d3fc4b8)       
    #>  Github (r-lib/rlang@0bce15a)            
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  Github (jonclayden/RNiftyReg@20c419f)   
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.0)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.2)                          
    #>  CRAN (R 4.0.0)                          
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by muschellij2** [comment]
I think these codes are obsolete:
https://github.com/jonclayden/RNiftyReg/blob/0b3408ee0786ecf60168bf4f501ba39a7710e97a/R/transform.R#L88
as the transformation has no attributes of source or target, and so nSourceDim is 0 and then all the if statements fail.

**Comment by jonclayden** [comment]
Admittedly this could probably be more transparent, but the intention is that you use `forward()` or `reverse()`, which set these attributes appropriately. So

```r
applyTransform(transform = forward(reg), x = mni)
```

should work as intended.
