### ISSUE TITLE
Setting niftyreg parameters to get a good 2D registration

### ISSUE THREAD

**Issue by DanRuderman** [jonclayden/RNiftyReg#16]
I'm having some strong sensitivity to some parameters passed to the rigid registration. I have found parameters that work for a particular example from my set of registrations, but they don't hold up with other examples. These parameters are very brittle. I'm wondering if there is a trick to getting this to work more generally?

I am using the latest source for RNiftyReg from GitHub.

Here is code showing a particular set of parameters that works and that the default without those parameters doesn't.
Data source files attached.

```
require(RNiftyReg)
require(mmand)

# load the source and target images
source <- readRDS('source.RDS')
target <- readRDS('target.RDS')

# What the answer should look like
display(target)

# this works
display(niftyreg(source, target, scope='rigid', nLevels=7L, maxIterations=7L, useBlockPercentage=80L )$image)

# this doesn't
display(niftyreg(source, target, scope='rigid', nLevels=7L, maxIterations=7L)$image)

# this doesn't
display(niftyreg(source, target, scope='rigid')$image)

[image_files.zip](https://github.com/jonclayden/RNiftyReg/files/5771473/image_files.zip)

```

**Comment by jonclayden** [comment]
Dan, I apologise for not getting to this issue. I think I had an initial look at your images, didn't come to an immediate conclusion and then lost track of it. It's true that a bit of fiddling with the parameters can be necessary. Are you still struggling with these registrations?

**Comment by DanRuderman** [comment]
Hi Jon. Not a problem. I'm no longer working on that project. Thanks for you work on this algorithm and for sharing it!
