### ISSUE TITLE
Error for large images

### ISSUE THREAD

**Issue by gangcai** [jonclayden/RNiftyReg#17]
<pre>
> result <- niftyreg(source, target)
[NiftyReg ERROR] Function: reg_tools_kernelConvolution_core
[NiftyReg ERROR] This function does not support images with dimension > 2048
Error in niftyreg.linear(source, target, scope, init, sourceMask, targetMask,  : 
  [NiftyReg] Fatal error
</pre>

**Comment by jonclayden** [comment]
Hi. This is a known limitation of the upstream NiftyReg functions (see also #15), and unfortunately it's not straightforward to work around. As a result this is unlikely to be changed unless the upstream authors generalise their code.
