### ISSUE TITLE
Trying to convert output of applyTransform() into image format (jpg, png, tiff, etc)

### ISSUE THREAD

**Issue by Jonathan-Gore** [jonclayden/RNiftyReg#18]
Hey,

I'm trying to convert the output of a pre-determined transformation matrix with applyTransform() (class: Large nifitImage) into an image, but I can't find a function to do so. Am I missing something obvious? Is there anyway for me to convert the Large niftiImage class into a base-R matrix for writing it to a jpg, png, or tiff image?

Thanks!

**Comment by jonclayden** [comment]
Hi! The result of `applyTransform()` _is_ a standard array or matrix by default (albeit with class `niftiImage`), so you shouldn't have to do anything special. But do let me know if you're still having trouble.

**Comment by jonclayden** [comment]
I assume this is resolved.
