### ISSUE TITLE
question on deformationField

### ISSUE THREAD

**Issue by chenyangliu2018** [jonclayden/RNiftyReg#19]
Nice work. The output of deformationField looks like a deformed mesh grid instead of deformation vector field (DVF). May I know how to get the DVF? Thanks.

**Comment by chenyangliu2018** [comment]
I edited  the motionfield by subtracting a meshgrid with 0:1:N-1, where N is the dimension size. I was wondering is that correct?

**Comment by jonclayden** [comment]
Hi. The [upstream codebase](https://github.com/KCL-BMEIS/niftyreg) includes a command-line tool called `reg_transform` which can convert between different transformation formats including deformation and displacement fields. Unfortunately there is no R interface to this, but that's the route I would recommend if possible, rather than modifying the field manually.

**Comment by chenyangliu2018** [comment]
Thanks for the reply. I will that one. Btw, I modified the field manually just now by using the method I mentioned. It seems it works.

**Comment by chenyangliu2018** [comment]
I am kind of new learner on MRI reconstruction. If I want to incorporate the RNifftyReg in to a conjugate iteration. Could I get the transpose of the motionfield from this package. If not, any suggestion on how to deal with it. Thank you very much.

**Comment by jonclayden** [comment]
Sorry, I'm not sure what you're trying to do from that information. What is the motion field you want? Can you give a concrete example?

**Comment by chenyangliu2018** [comment]
Hello, thank you for your response. Sorry I haven't explain my question well. The problem is if Iwant solve Mx = y, Imay need the M transpose, where M is the motionfield. I may have figured this problem out. My method is compose a sparse metrix that represent the motionfield and direct transpose it. Let me see whether it works or not.

**Comment by jonclayden** [comment]
I am assuming this is resolved – do reopen it if not, but I will need more information to be able to help.
