### ISSUE TITLE
Getting NiftyReg $image output as R matrix

### ISSUE THREAD

**Issue by NHPatterson** [jonclayden/RNiftyReg#2]
Hello, I have done some work transforming images using RNiftyReg and don't seem to find any documentation in getting a simple matrix  of the niftyreg$image as an output after registration. I've worked around this by writing the R object using WriteNifti and reading it through oro.nifti and extracted the image matrix from from @.Data in the oro.nifti class, but I must be missing something! Is there not a simple way to do this directly from RNiftyReg? 

Thanks,
Heath

**Comment by jonclayden** [comment]
Hi Heath. The `image` component of a `niftyreg` object *is* a matrix or array (albeit with class `niftiImage`). You shouldn't have to do anything.

**Comment by NHPatterson** [comment]
Thanks again, I figured it out, appreciate your work in bring imaging analysis to R! 

Heath
