### ISSUE TITLE
transforming image and points

### ISSUE THREAD

**Issue by Borda** [jonclayden/RNiftyReg#6]
Hello, I was using this nice package some time ago (back in 2015, I believe it was version 1.x) and since that time a few things changed... I want to update my script to be able to use the latest version of RNiftyReg, but am facing some difficulties with using output transformation and transforming source image (I noticed that is already part of the output but for practice) and some landmark coordinates.

Please see the two examples for Affine
https://github.com/Borda/BIRL/blob/RNiftyReg/scripts/Rscript/RNiftyReg_linear.r
and Non-linear registration
https://github.com/Borda/BIRL/blob/RNiftyReg/scripts/Rscript/RNiftyReg_elastic.r
the output errors are
```
Error in applyTransform(result$forwardTransforms[[1]], source) : 
  Object to transform should be a suitable image or matrix of points
Error in applyTransform(result$forwardTransforms[[1]], points) : 
  Object to transform should be a suitable image or matrix of points
```

@jonclayden do you have any advice on how to convert `source` and `points` to the proper format?

**Comment by Borda** [comment]
it seems that the transform `result$forwardTransforms` generated by `niftyreg.linear` or `niftyreg.nonlinear` does not contain `source` and `target` anymore...
https://github.com/jonclayden/RNiftyReg/blob/562b24a3206ffacfbca50bbe93baa49a5a650f7e/R/transform.R#L86
is it a version incompatibility, @jonclayden ?

**Comment by jonclayden** [comment]
Hi. The short answer is that you should extract the transform from the registration result with `forward()` (or `reverse()`), rather than trying to do it directly. That way the necessary information about the original source and target is retained (in attributes). So, instead of

```r
applyTransform(result$forwardTransforms[[1]], source)
```

you need

```r
applyTransform(forward(result), source)
```

**Comment by Borda** [comment]
@jonclayden And what about the supported image sizes?
```
During startup - Warning messages:
1: Setting LC_MONETARY failed, using "C" 
2: Setting LC_PAPER failed, using "C" 
3: Setting LC_MEASUREMENT failed, using "C" 
[NiftyReg ERROR] Function: reg_tools_kernelConvolution_core
[NiftyReg ERROR] This function does not support images with dimension > 2048
Error in niftyreg.linear(source, target, scope = c("affine", "rigid"),  : 
  [NiftyReg] Fatal error
Calls: niftyreg.linear -> .Call
Execution halted
```

**Comment by Borda** [comment]
@jonclayden it seems that the transformation does not work for nonlinear... The code is
```
result <- niftyreg.nonlinear(source, target,
                             estimateOnly=FALSE, verbose=TRUE)
result

## Transform image
imgWarp <- applyTransform( forward(result) , source)
## Save image as bitmap
png::writePNG(imgWarp@.Data, outImg)
```
and the error code
```
Error in getClass(class(object)) : 
  c("“niftiImage” is not a defined class", "“array” is not a defined class")
Calls: <Anonymous> -> getDataPart -> getClass
Execution halted
```

**Comment by jonclayden** [comment]
The image size limit is an upstream (NiftyReg) limitation, I'm afraid, so it's not something I can easily change.

As for the nonlinear case, the problem doesn't seem to be the transformation but the fact that you're using `@`, which is S4 slot notation. That was appropriate for `nifti` objects in version 1 of the package, but is no longer necessary (and, as you have found, will not work). You can just pass the image to `writePNG` as-is, viz. `png::writePNG(imgWarp, outImg)`.

**Comment by Borda** [comment]
Ok, it helps for saving the image, I overlooked it as I am not very familiar with R.

**Comment by Borda** [comment]
Would be a simple option how to downscale the images to the limit then upsample the output image and landmarks?

**Comment by jonclayden** [comment]
Yes, you could try that. The `rescale` function can be used to resize an image.
