### ISSUE TITLE
Display of transformed images

### ISSUE THREAD

**Issue by Veerle-Haemels** [jonclayden/RNiftyReg#7]
Dear Jon, 

First off I would like to thank you for the development of these tool packs.
They really do contribute to bringing image analysis into R!

As a starting PhD student (biomedical sciences), I have a basic knowledge of R (Studio).
The question/error below might seem obvious to you, but I was wondering how to fix it.

I'm interested in developing a pipeline consisting of a first rough registering, followed by cropping out the tissue-micro-array cores, followed by a detailed registration.
With finally also a segmenting pipeline following.

Below you can find some already cropped out cores, where I wanted to test the registration. Since there a limit on image size, I reduced the file sizes temporary.
Followed by doing a registration based on Core1. 

> Core1_resized <-resize(Core1,h=500)
> display(Core1_resized)
> Core2_resized <-resize(Core2,h=500)
> display(Core2_resized)
> Core3_resized <-resize(Core3,h=500)
> display(Core3_resized)
> ##Use resized_DAPI files for registration 
> transformation <- niftyreg(Core1_resized, Core2_resized, scope="affine")
> transformation <- niftyreg(Core1_resized, Core2_resized, scope="nonlinear", init=forward(transformation))

I'm testing out both linear and non linear transformations so see what fits best.
When wanting to apply these transformations
> transformed_Core2_resized<-applyTransform(forward(transformation), Core2_resized)
I get an error following the display command
> display(transformed_Core2_resized)
Error in (function (classes, fdef, mtable)  : 
 unable to find an inherited method for function ‘normalize’ for signature ‘"niftiImage"’

Do you have any suggestions on how to solve this?

As second question, I read that the image format preferred is .jpeg or .png, since .tiff is prone to acting up. I'm working with .tiff files and if not needed I would prefer using these files over conversion to .jpeg and loosing  information.

I'm looking into cell marker expression and there every (digital) signal picked might be of interest, since we also will be correcting for autofluorescence.

Thank you for your time!

**Comment by jonclayden** [comment]
Hi! First of all, working with TIFF images should be fine – you'll just need to use a suitable package such as `tiff` to load them into R. `RNiftyReg` works with standard R arrays, and the source format isn't important.

As for your main question, if I understand correctly the calls to `niftyreg()` and `applyTransform()` are running without errors, but you're having trouble viewing the result. Is that right? If so, could you clarify which package(s) the `resize()` and `display()` functions are from, please? It looks like the issue may be an incompatibility with `display()`.

All the best.

**Comment by AnneRademacher** [comment]
Hi!
I'm quite new to image analysis in R and I'm having the same problem with my FRAP data (also tiff format). I have time series with 1272 images (128x128 px) that I can read and register fine (the images are from live cell microscopy, so I use registration to account for drift or movement of the cell over time). I can also display and save single images (in tiff format after replacing NaNs with 0): 

`data <- imageData(channel(readImage(paste0(folder,"/",file[i])), 'g'))`
`display(data)`
`result <- niftyreg(source = data, target = data[,,1], scope = "rigid")`
`display(result$image[,,1000])`
`test <- result$image`
`test[is.nan(test)] <- 0`
`writeImage(test[,,1000], "/Users/AnneRademacher/Desktop/test.tiff")`

However, displaying or saving the entire image stack yields the same error as mentioned by @Veerle-Haemels:

`display(result$image)`
> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘normalize’ for signature ‘"niftiImage"’

`writeImage(test, "/Users/AnneRademacher/Desktop/test.tiff")`
> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘normalize’ for signature ‘"niftiImage"’

I'm using the EBImage package (version 4.24.0) for `display()` and `writeImage()` and RNiftyReg version 2.6.6.
`library(RNiftyReg)`
`library(EBImage)`

I'd appreciate any help. Thanks in advance!

**Comment by jonclayden** [comment]
Hi Anne, and thanks for clarifying that you're using `EBImage`'s `display()` function. As I suspected, I think it's an incompatibility somewhere down the stack in that package, but it seems to be specific to their "browser" viewer, so if you use

```r
display(result$image, method="raster")
```

I think it should work as expected.
