### ISSUE TITLE
Provide interrupt abilities?

### ISSUE THREAD

**Issue by mpadge** [jonclayden/RNiftyReg#8]
@jonclayden Thanks for your fabulous package, and congrats on your supremely clean code - it is indeed most impressive! I've written a package which depends on `RNiftyReg`, and uses it to rectify [images of maps](https://github.com/mpadge/mapscanner). My package is currently [under review for rOpenSci](https://github.com/ropensci/software-review/issues/330), and a reviewer (ping @potterzot) noted that there is [no way to interrupt the function](https://github.com/ropensci/software-review/issues/330#issuecomment-524492943), and furthermore that it did not exit cleanly (maybe extending from #3). I have no reproducible code for the latter claim, but would nevertheless like to ask whether you might incorporate an interrupt function?

It seems, from my crude perusal, that you could just `include <R.h>` in your [`_reg_aladin.cpp`](https://github.com/jonclayden/RNiftyReg/blob/master/src/reg-lib/_reg_aladin.cpp), and then just use `if (l % 1000 == 0) R_CheckUserInterrupt()` or something like that. Would that be possible?

**Comment by jonclayden** [comment]
Hi! The ability to interrupt registration in this way was added in v2.3.0, but it looks like this may have been accidentally undone (for linear registration in particular) during an upstream update since then. I will look into it.

**Comment by jonclayden** [comment]
This should now be resolved. Thanks for the report!

**Comment by mpadge** [comment]
Thanks for the really quick response - nice work!
