### ISSUE TITLE
Mask function working erradically

### ISSUE THREAD

**Issue by christmanjc** [jonclayden/RNiftyReg#9]
Hi,
I am using the RniftyReg package to do register 2 images. I am trying to use the mask as a way to highlight the key area of the image I want used for the registration. I am getting error when I make a mask that is about 10% of the image. If I make the mask larger it seems to work. Is there some sort of limit on how many pixels must be active in the mask?

[NiftyReg ERROR] Function: initialise_block_matching_method()
[NiftyReg ERROR] There are no active blocks
Error in niftyreg.linear(source, target, scope, init, sourceMask, targetMask,  : 
  [NiftyReg] Fatal error

**Comment by jonclayden** [comment]
Yes – from memory the block size is 4 pixels in each dimension, so the mask would need to cover at least that size.

**Comment by christmanjc** [comment]
I am bit confused. I am using images (source and target) of size (1800,2000,3). Then i try apply a mask on target like this and get the error:
maskUsed<-array(0,dim=c(1800,2000))
maskUsed[300:1800,300:2000]<-1
reg<-niftyreg(one,two,scope='rigid',targetMask = maskUsed,symmetric = TRUE)

[NiftyReg ERROR] Function: initialise_block_matching_method()
[NiftyReg ERROR] There are no active blocks
Error in niftyreg.linear(source, target, scope, init, sourceMask, targetMask, :
[NiftyReg] Fatal error



If i change my mask to the whole image being used as mask then it works.
maskUsed<-array(0,dim=c(1800,2000))
maskUsed[1:1800,1:2000]<-1
reg<-niftyreg(one,two,scope='rigid',targetMask = maskUsed,symmetric = TRUE)


Maybe i am misunderstanding the mask?
Thanks

**Comment by jonclayden** [comment]
Hmm, OK. It’s not obvious to me what’s going on here. Are you able to make your source and target images available so that I can give it a try?

**Comment by christmanjc** [comment]
I am not able to share the images that i am working with. So in theory this should be working right? That i can define a non-zero region in the image to use as my mask?

**Comment by jonclayden** [comment]
That’s the intent, yes. As long as there’s information in that region of the image (in particular, its intensity variance is not zero) it should be OK. Note also that, as your third dimension is 3, `RNiftyReg` will assume this is a three-channel image and average across channels before it starts the registration. Other than that, I’m afraid I don’t think I can help further without a reproducible example.

**Comment by christmanjc** [comment]
Ok. Let me try to replicate with shareable images. Have you tried this on images that you have?

**Comment by christmanjc** [comment]
Here is my example with images and code.
[to send.zip](https://github.com/jonclayden/RNiftyReg/files/4199683/to.send.zip)

**Comment by jonclayden** [comment]
Thanks. I can reproduce the issue – I’m looking into it.

**Comment by jonclayden** [comment]
Phew, this issue took quite an effort to track down! I’ve pushed a commit to `master` which fixes it for me in your example - would you mind giving it a try on your original images, please?

**Comment by christmanjc** [comment]
Sorry for my late reply as i have been in and out of the office. To try
your fix, i would need to get the niftyreg from GitHub? Or can i simply
update via R through Cran? Sorry for the stupid question but i really dont
use github.
Jeremy

**Comment by jonclayden** [comment]
Yes, you'll just need to pull the latest version of the package from GitHub. The easiest way to do that is with the `remotes` package:

```r
install.packages("remotes")
remotes::install_github("jonclayden/RNiftyReg")
```

**Comment by christmanjc** [comment]
I am getting error when trying to install package from github.

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("remotes")
Installing package into ‘C:/Users/christman.jc/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL '
https://cran.rstudio.com/bin/windows/contrib/3.5/remotes_2.1.1.zip'
Content type 'application/zip' length 355102 bytes (346 KB)
downloaded 346 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\christman.jc\AppData\Local\Temp\RtmpKMqUWA\downloaded_packages
> remotes::install_github("jonclayden/RNiftyReg")
Downloading GitHub repo jonclayden/RNiftyReg@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All
2: CRAN packages only
3: None
4: Rcpp (0.12.19 -> 1.0.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
Rcpp (0.12.19 -> 1.0.3) [CRAN]
Installing 1 packages: Rcpp
Installing package into ‘C:/Users/christman.jc/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/Rcpp_1.0.3.zip'
Content type 'application/zip' length 3011892 bytes (2.9 MB)
downloaded 2.9 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\christman.jc\AppData\Local\Temp\RtmpKMqUWA\downloaded_packages
Running `R CMD build`...
* checking for file
'C:\Users\christman.jc\AppData\Local\Temp\RtmpKMqUWA\remotesda83b6b70a8\jonclayden-RNiftyReg-e9f9fdd/DESCRIPTION'
... OK
* preparing 'RNiftyReg':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'RNiftyReg_2.6.7.tar.gz'
Installing package into ‘C:/Users/christman.jc/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'RNiftyReg' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'RNiftyReg'
* removing 'C:/Users/christman.jc/Documents/R/win-library/3.5/RNiftyReg'
* restoring previous
'C:/Users/christman.jc/Documents/R/win-library/3.5/RNiftyReg'
In R CMD INSTALL
Error: Failed to install 'RNiftyReg' from GitHub:
  (converted from warning) installation of package
‘C:/Users/CHRIST~1.JC/AppData/Local/Temp/RtmpKMqUWA/fileda874b833d8/RNiftyReg_2.6.7.tar.gz’
had non-zero exit status
In addition: Warning message:
In missing_devel_warning(pkgdir) :
  Package RNiftyReg has compiled code, but no suitable compiler(s) were
found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use
the pkgbuild package, or make sure that Rtools in the PATH.

**Comment by jonclayden** [comment]
Ah, clearly you don’t have a suitable compiler toolchain installed. You could try the AppVeyor build at https://ci.appveyor.com/api/buildjobs/lll4lmofsg2sljtf/artifacts/RNiftyReg_2.6.7.zip, but if that doesn’t work or is too much hassle then I’ll just go ahead and push a release for you to try.

**Comment by christmanjc** [comment]
It would be easier for me if you pushed the release. but, if you prefer me
to try to load up from the link you sent i can give that a try.
Jeremy

**Comment by jonclayden** [comment]
Sorry for the delay – recent events have obviously been quite disruptive. An updated version of the package, v2.6.8, is now on CRAN with the fix applied. Windows binary versions should appear there in the next day or two.

**Comment by jonclayden** [comment]
Closing this issue for now. Do reopen it if you see the problem recur.
